POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiaGlsbG92YWxrb3NpcHVsaSIsImlkIjoiNWU5YjI4ZDhkNWZlM2QxZWM0YjNiNTMzIiwiaWF0IjoxNTg3MzA3MDEzfQ.9kp6F9GPiKdIxeKm4nA4RAYhCU4T_hv_4PExrDgjEzI

{
    "title": "Authorized Blog",
    "author": "A Chef with a Cooking License",
    "url": "/Ph/D"
}
